### ISSUE TITLE
使用问题咨询

### ISSUE THREAD

**Issue by johntaiii** [waimaiditu/map#1]
Hello，赞一下想法，确实是哥痛点，设计也很棒！
使用插件的时候碰到两个问题：
1.传入经纬度参数没生效，一直都是天安门
2.只能显示卫星图？

![](https://tva1.sinaimg.cn/large/006y8mN6gy1g741tq1pfsj31i80u0kiy.jpg)

**Comment by johntaiii** [comment]
进入插件页面控制台会报如下错：
![](https://tva1.sinaimg.cn/large/006y8mN6gy1g74ox226ybj30xa02qn0f.jpg)

**Comment by fuweijun** [comment]
感谢提交issue，这两个问题在1.1.0版本已修复，请尝试更新插件版本。

**Comment by fuweijun** [comment]
卫星图层开关下个版本1.1.1中会更新上去。

**Comment by fuweijun** [comment]
是否显示卫星图可以通过传参配置

**Comment by johntaiii** [comment]
> 是否显示卫星图可以通过传参配置

你好，是通过enableSatellite 控制吗？已经设置成false了，还是显示卫星图

**Comment by fuweijun** [comment]
> > 是否显示卫星图可以通过传参配置
> 
> 你好，是通过enableSatellite 控制吗？已经设置成false了，还是显示卫星图

确认下插件版本是1.1.0么？

**Comment by fuweijun** [comment]
可以查找 QQ群 717067303 并加入地图编辑插件交流群讨论
